version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2

executors:
  ruby27:
    docker:
      - image: circleci/ruby:2.7-node-browsers
  ruby26:
    docker:
      - image: circleci/ruby:2.6-node-browsers

jobs:
  breezy:
    executor: ruby27
    steps:
      - checkout
      - run:
          name: NPM Install
          working_directory: ./breezy
          command: npm install
      - run:
          name: Lint
          working_directory: ./breezy
          command: npm run lint
      - run:
          name: Test
          working_directory: ./breezy
          command: npm run test
  breezy-rails:
    parameters:
      ruby-version:
        type: executor
      gemfile:
        type: string
    executor: << parameters.ruby-version >>
    steps:
      - checkout
      - run:
          name: Which bundler?
          working_directory: ./breezy_rails
          command: bundle -v
      - run:
          name: Using Gemfile
          working_directory: ./breezy_rails
          command: mv -f ./<< parameters.gemfile >> ./Gemfile
      - run:
          name: Bundle install
          working_directory: ./breezy_rails
          command: bundle install
      - run:
          name: Rake Test
          working_directory: ./breezy_rails
          command: bundle exec rake test
      - run:
          name: Acceptance Test
          working_directory: ./breezy_rails
          command: BUNDLE_GEMFILE='' ruby -Ilib:test test/acceptance/breezy_installation_acceptance.rb

workflows:
  tests:
    jobs:
      - breezy
      - breezy-rails:
          matrix:
            parameters:
              gemfile:
                - Gemfile.rails60
                - Gemfile.rails61
              ruby-version:
                - ruby26
                - ruby27
